name: ci
on: [push]
jobs:
  # https://docs.knapsackpro.com/2021/how-to-run-ruby-on-rails-tests-on-github-actions-using-rspec
  test:
    runs-on: ubuntu-latest
    services:
      # https://github.com/actions/example-services/blob/master/.github/workflows/postgres-service.yml
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        # tmpfs makes DB faster by using RAM
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      DATABASE_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Rails verifies the time zone in DB is the same as the time zone of the Rails app
      TZ: "Europe/Prague"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install packages
        run: yarn install --pure-lockfile
      - name: Create DB
        run: bundle exec rails db:setup
      - name: Precompile assets
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: |
          bundle exec rails assets:precompile 
          bundle exec ./bin/vite build
      - uses: actions/upload-artifact@v3
        with:
          name: assets
          path: |
            public/assets
            public/packs
            public/vite
          retention-days: 1
      - name: RSpec
        run: bundle exec rspec
  deploy:
    runs-on: ubuntu-latest
    needs: "test"
    if: success() && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/download-artifact@v3
        with:
          name: assets
          path: public/
      - name: Read version
        run: APP_VERSION=$(cat ./version); echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: luk4s/home_control:latest,luk4s/home_control:${{ env.APP_VERSION }}
